################################################################################
# Utilitary functions that can be easily reused in other projects

#---------------------------------
join.path <- function(...) {
  paste(..., sep="/")
}

stem <- function(fpath) {
  basename(tools::file_path_sans_ext(fpath))
}

plot.save.list <- function(plot.list, out.dir, out.fname, ncol=1, height=NA, width=NA) {
  print(paste("Saving to", out.fname))
  out.fpath <- join.path(out.dir, out.fname)
  out.plots = marrangeGrob(grobs=plot.list, nrow = 1, ncol = ncol, top=NULL)
  ggsave(out.fpath, out.plots, height = height, width = width, units = "cm") # dpi=300
}

on.error.unrecg <- function(var.name, var.value) {
  paste0("unrecognized ", var.name, " '", var.value, "'")
}

prepare.out.dir <- function(dir.path) {
  if(dir.exists(dir.path)) {
    unlink(join.path(dir.path, "*"))
  } else {
    dir.create(dir.path)
  }
}

#--------------------------------
#' Convert ggplot plot to plotly and saves to a html file, reloading
#' chrome afterwards
#' @param p ggplot object
#' @param out.file file path for the html output
#' @param script.file javascript file with code to be appended to the html file
plot.to.browser <- function(p, out.file, script.file="") {
  ## pp <- ggplotly(p, tooltip = c("Score", "Alpha", "Shift", "Blur", "ImgComb", "text"))
  pp <- ggplotly(p, tooltip = c("text"))
  if(script.file != "") {
    plot.script <- read.file.str(script.file)
    # plot.script <- js::uglify_optimize(plot.script)
    pp <- htmlwidgets::appendContent(pp, htmltools::tags$script(htmltools::HTML(plot.script), type="application/javascript"))
  }
    htmlwidgets::saveWidget(pp, out.file)
  ## reload.chrome()
  ## reload.firefox()
  reload.plotly.window()
}

#--------------------------------
#' Send "Ctrl+r" to the first Google Chrome window open
reload.chrome <- function() {
  xdo.reload("class", "chrome")
}

#--------------------------------
#' Send "Ctrl+r" to the first Firefox window open
#'   OBS: firefox is better because it doesn't change windows focus after
#'        window.open() call inside the plot page
reload.firefox <- function() {
  xdo.reload("class", "firefox")
}

#--------------------------------
#' Send "Ctrl+r" to the first window named 'plotly', which is the default name
#' for html files generated by htmlwidgets::saveWidget()
#' The "^" before plotly indicates the window names starts with "plotly"
#' The ".*" will match any program name (ex. Mozilla Firefox, Chrome...)
#' xdotool uses case-insensitive POSIX Extended Regular Expressions
#' ref: https://github.com/jordansissel/xdotool/issues/172
reload.plotly.window <- function() {
  xdo.reload("name", "\"^plotly - .*$\"")
}

#--------------------------------
#' Send "Ctrl+r" to a window of the given name
#' @param option.name "name" for WINDOW name. "class" for PROCESS command name
#' @param target the argument for the corresponding option
xdo.reload <- function(option.name=c("name", "class"), target) {
  option <- paste0("--", option.name)
  option.spec <- paste0(option, " ", target)
    cmd <- paste0("focused_window_id=$(xdotool getwindowfocus); xdotool search --onlyvisible ", option.spec, " windowfocus key 'ctrl+r'; xdotool windowactivate --sync $focused_window_id")
  system(cmd, wait=F, ignore.stdout = T, ignore.stderr = T)
}
